<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.1.375
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envío de Formulario Inicio',
	'heading' => 'Envío de nuevo formulario',
	'success_redirect' => '',
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U90' => array(
			'type' => 'string',
			'label' => 'Usuario',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Usuario\' es obligatorio.'
			)
		),
		'Email' => array(
			'type' => 'email',
			'label' => 'Contraseña',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Contraseña\' es obligatorio.',
				'format' => 'El campo \'Contraseña\' contiene un correo electrónico no válido.'
			)
		)
	)
);

process_form($form);
?>
